# Generated by Django 4.0.1 on 2022-01-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='other_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
