# Generated by Django 4.0.1 on 2022-01-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_applicant_phone_number_alter_applicant_other_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
