# Generated by Django 4.0.1 on 2022-01-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0005_remove_course_applicant_course_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='applicant',
        ),
        migrations.AddField(
            model_name='applicant',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='schema.Course'),
        ),
    ]
