# Generated by Django 4.0.1 on 2022-01-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0007_course_tutor_alter_applicant_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='course',
            name='thumb_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics_thumbs'),
        ),
    ]
