# Generated by Django 4.0.1 on 2022-01-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0008_course_photo_course_thumb_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro_video_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
