# Generated by Django 4.0.1 on 2022-01-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0009_course_intro_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='intro_video_link',
        ),
        migrations.AddField(
            model_name='course',
            name='intro_video_embed_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
